spring:
  application:
    name: api-jobs
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_DIALECT}
    show-sql: true

api:
  key: ${API_KEY}
  url: ${API_URL}

